"""HTML exporter using Jinja2 with fallback template"""

import logging
from pathlib import Path
from typing import Any, Dict
from datetime import datetime, timezone

try:
    from jinja2 import Environment, FileSystemLoader, select_autoescape
    JINJA2_AVAILABLE = True
except ImportError:
    JINJA2_AVAILABLE = False

logger = logging.getLogger("anomradar.exporters.html")


def export_html(data: Dict[str, Any], output_path: Path) -> None:
    """Export scan results to HTML file using Jinja2
    
    Uses Jinja2 templates with fallback to simple template.
    
    Args:
        data: Scan results dictionary
        output_path: Path to output HTML file
    """
    logger.info(f"Exporting HTML to {output_path}")
    
    if not JINJA2_AVAILABLE:
        logger.warning("Jinja2 not available, using basic HTML export")
        _export_html_basic(data, output_path)
        return
    
    try:
        # Setup Jinja2 environment
        template_dir = Path(__file__).parent.parent / "reports"
        
        # Try main template first, fallback if not found
        try:
            env = Environment(
                loader=FileSystemLoader(str(template_dir)),
                autoescape=select_autoescape(['html', 'xml'])
            )
            template = env.get_template("html_template.html")
        except Exception as e:
            logger.warning(f"Main template failed, using fallback: {e}")
            template = env.get_template("html_template_fallback.html")
        
        # Prepare template context
        # Extract target from first scanner result
        target = "Unknown"
        for scanner_data in data.values():
            if "target" in scanner_data:
                target = scanner_data["target"]
                break
        
        context = {
            "target": target,
            "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            "results": data
        }
        
        # Render and save
        html_content = template.render(**context)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        logger.info(f"HTML export completed: {output_path}")
        
    except Exception as e:
        logger.error(f"HTML export failed: {e}", exc_info=True)
        logger.info("Falling back to basic HTML export")
        _export_html_basic(data, output_path)


def _export_html_basic(data: Dict[str, Any], output_path: Path) -> None:
    """Basic HTML export without Jinja2 (fallback)"""
    target = "Unknown"
    for scanner_data in data.values():
        if "target" in scanner_data:
            target = scanner_data["target"]
            break
    
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AnomRadar Scan Report - {target}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }}
        .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 20px; }}
        h1 {{ color: #333; }}
        .scanner {{ margin: 20px 0; padding: 15px; border: 1px solid #ddd; }}
        .success {{ background: #e8f5e9; }}
        .error {{ background: #ffebee; }}
        pre {{ background: #f4f4f4; padding: 10px; overflow-x: auto; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔒 AnomRadar Security Scan Report</h1>
        <p><strong>Target:</strong> {target}</p>
        <p><strong>Generated:</strong> {timestamp}</p>
"""
    
    for scanner_name, scanner_data in data.items():
        status_class = "success" if scanner_data.get("success") else "error"
        status_text = "✓ Success" if scanner_data.get("success") else "✗ Failed"
        
        html += f"""
        <div class="scanner {status_class}">
            <h2>{scanner_name.upper()}</h2>
            <p><strong>Status:</strong> {status_text}</p>
            <p><strong>Message:</strong> {scanner_data.get('message', 'N/A')}</p>
"""
        
        if "data" in scanner_data:
            import json
            html += f"""
            <h3>Data:</h3>
            <pre>{json.dumps(scanner_data['data'], indent=2)}</pre>
"""
        
        html += "        </div>\n"
    
    html += """
        <p style="text-align: center; margin-top: 30px; color: #666;">
            Generated by AnomRadar v2.0
        </p>
    </div>
</body>
</html>
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)
    
    logger.info(f"Basic HTML export completed: {output_path}")
